# ruta main (web)
route = '/'

# Mi token
token = 'ODY0OTMwMTU2ODU3Nzg2Mzg4.YO8m-w.Vmzq6Ra6q55v1wF0HF2vDYFJe8E'

# Mi ID
owner = ["795127511204888596", "401845716991082496", "342382341185994757", "910543706489237544"]

# Coneccion a mongo
MongoDB_URL = "mongodb+srv://sophiauser:otFJOnzjCP0lSgVy@cluster0.p0yum.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

# Tiempo minimo para eliminar mensajes
deleteTime = "5000"

# ID del canal para el guildCreate
serverID = '915230633280823336'

# ID del Bot
botId = '864930156857786388'

# channels Report
report_channel = '900017404443263036' # la id se puede cambiar