name: Tests

on: [push, pull_request]

jobs:
    avoid_reduncy:
        runs-on: ubuntu-20.04
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

    lint:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run eslint
